version: "3.9"
services:
  web:
    container_name: web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/tmp/pids 
      - /app/node_modules