production:
  clients:
    default:
     # The standard MongoDB connection URI allows for easy
     # replica set connection setup.
     # Use environment variables or a config file to keep your
     # credentials safe e.g. <%= ENV['MONGODB_URI'] %>.
    #  uri: mongodb://username:password@host1:port1,host2:port2/database?replicaSet=<replicaSetName>
     uri: <%= ENV['MONGODB_URI'] %>
     options:
       # The default timeout is 5, which is the time in seconds
       # for a connection to time out.
       # We recommend 15 because it allows for plenty of time
       # in most operating environments.
       connect_timeout: 15
       retry_writes: true
  options:
    raise_not_found_error: false

staging: #copy production
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15
        retry_writes: false
  options:
    raise_not_found_error: false

development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: app_development
      hosts:
        - <%= ENV['MONGODB_URI'].present? ? ENV['MONGODB_URI'] : 'localhost:27017' %>
      options:
        retry_writes: false
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: app_test
      hosts:
        - <%= ENV['MONGODB_URI'].present? ? ENV['MONGODB_URI'] : 'localhost:27017' %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
        retry_writes: false
  options:
    raise_not_found_error: false
